### ISSUE TITLE
Provide list of sensor

### ISSUE THREAD

**Issue by hieuletrung** [hieuletrung/iot-alljoyn#3]
Update the title and description after selected the sensor.

**Comment by khanhduyn** [comment]
order sensor
Ten - so luong - don gia - total - link
Ultrasonic ranging module - x2 - 90 - 180 - http://www.tme.vn/Product.aspx?id=1596
Distance Measuring Sensor - x1 - 290 - 290 - http://www.tme.vn/Product.aspx?id=1514#page=pro_info
One-Wire Digital Thermometer - x1 - 27 - 27 - http://www.tme.vn/Product.aspx?id=264#page=pro_info

**Comment by khanhduyn** [comment]
Ultrasonic ranging module    - x2 - 90 - 180 - http://www.tme.vn/Product.aspx?id=1596
One-Wire Digital Thermometer - x2 - 27 -  54 - http://www.tme.vn/Product.aspx?id=264
LM35                         - x3 - 22 -  66 - http://www.tme.vn/Product.aspx?id=271
Photoresistor                - x5 -  6 -  30 - http://www.tme.vn/Product.aspx?id=691
PIR Motion Detector Module   - x2 - 70 - 140 - http://www.tme.vn/Product.aspx?id=572

----------------------------------------------------------------------------------
Total: 180 + 54 + 66 + 30 + 140 = 470
