### ISSUE TITLE
How to discover AJ service on Android

### ISSUE THREAD

**Issue by hieuletrung** [hieuletrung/iot-alljoyn#9]

**Comment by lyhh** [comment]
https://allseenalliance.org/developers/learn/core/about-announcement/interface : See "Discovery Calls Flow" for general understanding.

**Comment by hieuletrung** [comment]
Per https://allseenalliance.org/developers/develop/api-guide/about/linux#register-the-new-aboutlistener-and-call-whoimplements-

We can specific * to listen on all interfaces for WhoImplements function.

**Comment by hieuletrung** [comment]
Maybe using something like com.gcs.*
